// Generated by CoffeeScript 1.6.3
(function() {
  var addInchOutListener, slideOff, slideOn, slideToggle;

  window.sliderHidden = true;

  slideOn = function() {
    $(".slideout-ascii").off('mouseenter mouseleave');
    $(".slideout-ascii").removeClass("inchOut");
    return $(".slideout-ascii").addClass("slide");
  };

  slideOff = function() {
    $(".slideout-ascii").removeClass("slide");
    return addInchOutListener();
  };

  slideToggle = function() {
    if (window.sliderHidden) {
      slideOn();
      return window.sliderHidden = false;
    } else {
      slideOff();
      return window.sliderHidden = true;
    }
  };

  addInchOutListener = function() {
    $(".slideout-ascii").on('mouseenter', function() {
      return $(this).addClass('inchOut');
    });
    return $(".slideout-ascii").on('mouseleave', function() {
      return $(this).removeClass('inchOut');
    });
  };

  $(function() {
    $(".slideout_background").on('click', slideToggle);
    return addInchOutListener();
  });

}).call(this);
